#swagger:
#  title: 梦学谷博客系统接口文档
#  description: 梦学谷博客系统-分类&标签&文章&广告管理接口
#  exclude-path: /error # 剔除请求
#
#server:
#  port: 8001
#  servlet:
#    context-path: /article # 上下文件路径，请求前缀 ip:port/article
#
#spring:
#  application:
#    name: article-server # 应用名
#  # 数据源配置
#  datasource:
#    username: root
#    password: root
#    url: jdbc:mysql://192.168.0.11:3306/junyu_blog_article?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&allowMultiQueries=true
#    #mysql8版本以上驱动包指定新的驱动类
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    #   数据源其他配置, 在 DruidConfig配置类中手动绑定
#    initialSize: 8
#    minIdle: 5
#    maxActive: 20
#    maxWait: 60000
#    timeBetweenEvictionRunsMillis: 60000
#    minEvictableIdleTimeMillis: 300000
#    validationQuery: SELECT 1 FROM DUAL
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 192.168.0.11:8848 # 关于nacos注册与发现的配置, 配置nacos服务器的ip:port
#
#
#mybatis-plus:
#  type-aliases-package: com.mengxuegu.blog.entities
#  # xxxMapper.xml 路径
#  mapper-locations: classpath*:com/mengxuegu/blog/article/mapper/**/*.xml
#
## 日志级别，会打印sql语句
#logging:
#  level:
#    com.mengxuegu.blog.article.mapper: debug
#
#mengxuegu:
#  blog:
#    # 阿里云配置
#    aliyun:
#      # 要带上 https:// ,上传时要使用的
#      endpoint: https://oss-cn-shenzhen.aliyuncs.com
#      accessKeyId: LTAI4Fn3fcVPNwKg9X7i8nLJ # 根据自己的帐号配置
#      accessKeySecret: sxsbEIsCmP2ORSmMqjUe7jXHuuhue9 # 根据自己的帐号配置
#      bucketName: mengxuegu # 存储空间名称
#      # Bucket域名，访问文件时作为URL前缀，注意要加上 https:// 和 结尾带上 /
#      bucketDomain: https://mengxuegu.oss-cn-shenzhen.aliyuncs.com/
#
#
#
#
